build:
  desc: complile go binary
  cmds: 
    - go build

clean:
  desc: remove binaries
  cmds:
    - rm go_template

staging:
  desc: push to heroku staging
  deps: [build]
  cmds:
    - git push staging master

migrate_down:
  desc: migrate down
  cmds:
    - sql-migrate down

migrate_up:
  desc: migrate up
  cmds:
    - sql-migrate up

production:
  desc: push to heroku production
  deps: [build]
  cmds:
    - git push production master

serve:
  desc: builds and executes app binary
  deps: [clean, build]
  cmds:
    - ./go_template
